Documentation
osism/openstack-image-manager pull request #233
Opened 2022-02-02 13:16 UTC by ra-rau

Add documentation instead of Readme written in Sphinx.
Close issue#230

Signed-off-by: Ramona Rautenberg <rautenberg@osism.tech>

2022-02-06 10:25 UTC, berendt requested changes

2022-02-06 10:25 UTC, berendt commented on documentation/source/conf.py
> +    'github_version': 'master',
This should be main instand of master.

2022-02-06 10:25 UTC, berendt commented on documentation/tox.ini
> +[testenv:push]
The Push Environment Can be Removed.

2022-02-06 10:25 UTC, berendt commented on documentation/source/index.rst
> +OpenStack Image Manager
Add a ==== line First.

2022-02-06 10:25 UTC, berendt commented on documentation/source/contribute.rst
> +After creating a PR, please check the result of the Travis CI and correct any
Today we use GitHub Actions.

2022-02-06 10:25 UTC, berendt commented on documentation/source/configuration.rst
> +-----------------
Use ======= instead of ————-.

2022-02-07 06:23 UTC, ra-rau commented on documentation/source/conf.py
> +    'github_version': 'master',
Done

2022-02-07 06:23 UTC, ra-rau commented on documentation/tox.ini
> +[testenv:push]
Done

2022-02-07 06:23 UTC, ra-rau commented on documentation/source/index.rst
> +OpenStack Image Manager
Done

2022-02-07 06:23 UTC, ra-rau commented on documentation/source/contribute.rst
> +After creating a PR, please check the result of the Travis CI and correct any
Done

2022-02-07 06:23 UTC, ra-rau commented on documentation/source/configuration.rst
> +-----------------
Done

2022-02-16 09:04 UTC, merged