Add contribute.md for the new documentation
osism/openstack-image-manager pull request #426
Opened 2022-11-25 14:05 UTC by ra-beer

Signed-off-by: Ramona Beermann <ramona.beermann@osism.tech>

2022-11-26 13:44 UTC, berendt requested changes

2022-11-26 13:44 UTC, berendt commented on doc/source/contribute.md
> +To prioritize the import of a new image [Contact Us](mailto:info@osism.tech)  with reference to the created pull request.
double space before ``with``

2022-11-26 13:44 UTC, berendt commented on doc/source/contribute.md
> +[OpenStack Image Manager](https://github.com/osism/openstack-image-manager) repository.
Would prefer to link ``GitHub repository`` instead of only ``GitHub``.

2022-11-26 13:44 UTC, berendt commented on doc/source/contribute.md
> +After creating a pull request, please check the result of the GitHub Actions and correct any errors identified.
GitHub Actions --> Zuul

2022-11-26 13:44 UTC, berendt commented on .github/workflows/check-markdown-syntax.yml
> +      - run: markdownlint -c .markdownlint.yaml .
This should be a Zuul job. Also please open a 2nd PR for this.

2022-11-26 13:58 UTC, ra-beer commented on doc/source/contribute.md
> +To prioritize the import of a new image [Contact Us](mailto:info@osism.tech)  with reference to the created pull request.
done

2022-11-26 14:00 UTC, ra-beer commented on doc/source/contribute.md
> +[OpenStack Image Manager](https://github.com/osism/openstack-image-manager) repository.
The link is in the word OpenStack Image Manager.
It should shows like GitHub OpenStack Image Manager repository.
And if you klick on OpenStack Image Manager you should redirected to the right repo

2022-11-26 14:01 UTC, ra-beer commented on doc/source/contribute.md
> +After creating a pull request, please check the result of the GitHub Actions and correct any errors identified.
Done

2022-11-26 14:01 UTC, ra-beer commented on .github/workflows/check-markdown-syntax.yml
> +      - run: markdownlint -c .markdownlint.yaml .
Will create another PR for linting via zuul

2022-12-16 09:49 UTC, berendt approved these changes

2022-12-16 09:51 UTC, merged